config/routes.rb
SisEscolar::Application.routes.draw do
  resources :provas

  resources :turma_materias

  resources :turmas

  resources :materias

  resources :professores

  resources :alunos

  root 'alunos#index'

end

app/models/prova.rb
class Prova < ActiveRecord::Base

  # prova -> aluno
  belongs_to :aluno #, foreign_key: :aluno_id

  # prova -> materia
  belongs_to :materia

  # define a média se maior que 6.0 aluno aprovado
  # verifica se todas as notas estão preenchidas
  def resultado
    return "Notas pendentes" if (self.nota1==0.0) or (self.nota2==0.0) or (self.nota3==0.0) or (nota4==0.0)
    return "Aprovado" if (self.nota1+self.nota2+self.nota3+self.nota4)/4 >6.0 else "Reprovado"
  end

  def cor_resultado
    return "label label-info" if (self.nota1==0.0) or (self.nota2==0.0) or (self.nota3==0.0) or (nota4==0.0)
    return "label label-success" if (self.nota1+self.nota2+self.nota3+self.nota4)/4 >6.0 else "label label-important"
  end


  # nota1, nota2, nota3, nota4, aluno_id e materia_id são campos obrigatórios
  validates_presence_of :nota1, :nota2, :nota3, :nota4, :aluno_id, :materia_id, message: "Campo em branco"

  #verifica campos numericos
  validates_numericality_of :nota1, :nota2, :nota3, :nota4, message: "Apenas números"

  # Verifica se aluno já existe para matéria
  validates :aluno_id, uniqueness: { scope: :materia_id, message: " e matéria já consta" }

  # chama o atributo nota_certa
  validate :nota_certa

  # nota de 0 a 10
  def nota_certa
    errors.add(:nota1, ' :Digite uma nota válida de 0 a 10') if nota1 > 10  or nota1 < 0
    errors.add(:nota2, ' :Digite uma nota válida de 0 a 10') if nota2 > 10  or nota2 < 0
    errors.add(:nota3, ' :Digite uma nota válida de 0 a 10') if nota3 > 10  or nota3 < 0
    errors.add(:nota4, ' :Digite uma nota válida de 0 a 10') if nota4 > 10  or nota4 < 0
  end
end

app/controllers/provas_controller.rb
class ProvasController < ApplicationController
  before_action :set_prova, only: [:show, :edit, :update, :destroy]

  # GET /provas
  # GET /provas.json
  def index
    if params[:form]
      @provas = Prova.where("aluno_id = :query", {query: params[:form][:aluno_id]})
    else
      @provas = Prova.all
    end
    #@provas = Prova.all
  end

  # GET /provas/1
  # GET /provas/1.json
  def show
  end

  # GET /provas/new
  def new
    @prova = Prova.new
  end

  # GET /provas/1/edit
  def edit
  end

  # POST /provas
  # POST /provas.json
  def create
    @prova = Prova.new(prova_params)

    respond_to do |format|
      if @prova.save
        format.html { redirect_to @prova, notice: 'Prova was successfully created.' }
        format.json { render action: 'show', status: :created, location: @prova }
      else
        format.html { render action: 'new' }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provas/1
  # PATCH/PUT /provas/1.json
  def update
    respond_to do |format|
      if @prova.update(prova_params)
        format.html { redirect_to @prova, notice: 'Prova was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @prova.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provas/1
  # DELETE /provas/1.json
  def destroy
    @prova.destroy
    respond_to do |format|
      format.html { redirect_to provas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prova
      @prova = Prova.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prova_params
      params.require(:prova).permit(:aluno_id, :materia_id, :nota1, :nota2, :nota3, :nota4)
    end
end

app/helpers/provas_helper.rb
module ProvasHelper
end

app/views/provas/_form.html.erb
<!-- legenda -->
<legend><%=  %>Provas</legend>

<%= form_for(@prova) do |f| %>

    <!-- Mostra os erros -->
    <% if @prova.errors.any? %>
        <div id="error_explanation">
          <h2><strong>Erros no preenchimento, verifique</strong></h2>
          <ul>
            <% @prova.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!-- mostra informações no select -->
    <div class="field">
      <%= f.label :Aluno %><br>
      <%= f.collection_select(:aluno_id, Aluno.order(:nome), :id, :nome, :prompt => false) %>
    </div>

    <!-- mostra informações no select -->
    <div class="field">
      <%= f.label :Matéria %><br>
      <%= f.collection_select(:materia_id, Materia.order(:nome), :id, :nome, :prompt => false) %>
    </div>

  <div class="field">
    <%= f.label :nota1 %><br>
    <%= f.text_field :nota1 %>
  </div>
  <div class="field">
    <%= f.label :nota2 %><br>
    <%= f.text_field :nota2 %>
  </div>
  <div class="field">
    <%= f.label :nota3 %><br>
    <%= f.text_field :nota3 %>
  </div>
  <div class="field">
    <%= f.label :nota4 %><br>
    <%= f.text_field :nota4 %>
  </div>

    <!-- Botão voltar -->
    <%= f.submit class: "btn btn-primary", remote: false do %>
        <i class="icon-share-alt icon-white"></i>
    <% end %>
<% end %>

app/views/provas/edit.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">
  <%= render 'form' %>
</div>

<!-- Botão para voltar a tela aluno aluno -->
<%= link_to 'Mostrar', @prova, :class => 'btn' %>
<%= link_to 'Voltar', provas_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#provas"
</script>

app/views/provas/index.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">

  <!-- legenda -->
  <legend>Lista de Provas</legend>

  <!-- Pesquisa -->
  <form class="navbar-form pull-left" style="padding-bottom: 20px;">
    <%= form_tag alunos_path, method: :get do  %>
        <!-- mostra informações no select -->
        <div class="field">
          <%= label :form, :Aluno %><br>
          <%= collection_select(:form, :aluno_id, Aluno.order(:nome), :id, :nome, :prompt => false) %>
          <%= submit_tag 'Buscar', :disable_with => "Buscando..." , :class=> "btn" %>
        </div>
    <% end %>
  </form>

  <!-- tabela com a listagem -->
  <table class="table table-hover table-bordered">
    <thead>
    <tr>
      <th>Aluno</th>
      <th>Matéria</th>
      <th>1ª Nota</th>
      <th>2ª Nota</th>
      <th>3ª Nota</th>
      <th>4ª Nota</th>
      <th>Resultado</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @provas.each do |prova| %>
      <tr>
        <td><%= prova.aluno.nome %></td>
        <td><%= prova.materia.nome %></td>
        <td><%= prova.nota1 %></td>
        <td><%= prova.nota2 %></td>
        <td><%= prova.nota3 %></td>
        <td><%= prova.nota4 %></td>
        <td>
           <!-- aprovado fica verde se não laranja -->
           <span class="
                   <%= prova.cor_resultado %>">
                   <%= prova.resultado %>
           </span>
        </td>


        <!-- Visualizar -->
        <td width="30px">
          <%= link_to prova, class: "btn btn-info", remote: false do %>
              <i class="icon-eye-open icon-white"></i>
          <% end %>
        </td>

        <!-- editar -->
        <td width="30px">
          <%= link_to edit_prova_path(prova), class: "btn btn-success", remote: false do %>
              <i class="icon-edit icon-white"></i>
          <% end %>
        </td>

        <!-- Deletar -->
        <td width="30px">
          <%= link_to prova, method: :delete, data: { confirm: 'Você tem certeza?' } , class: "btn btn-danger", remote: false do %>
              <i class="icon-trash icon-white"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </table>
</div>

<!-- Btn add -->
<%= link_to 'Lançar Provas', new_prova_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#provas"
</script>

app/views/provas/new.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">
  <%= render 'form' %>
</div>

<br />

<!-- Botão voltar -->
<%= link_to 'Voltar', provas_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#provas"
</script>

app/views/provas/show.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">

  <!-- Legenda -->
  <legend>Prova</legend>

  <p>
    <strong>Aluno:</strong>
    <%= @prova.aluno.nome %>
  </p>

  <p>
    <strong>Materia:</strong>
    <%= @prova.materia.nome %>
  </p>

  <p>
    <strong>1ª nota:</strong>
    <%= @prova.nota1 %>
  </p>

  <p>
    <strong>2ª nota:</strong>
    <%= @prova.nota2 %>
  </p>

  <p>
    <strong>3ª nota:</strong>
    <%= @prova.nota3 %>
  </p>

  <p>
    <strong>4ª nota:</strong>
    <%= @prova.nota4 %>
  </p>
</div>
<!-- Botão voltar -->
<%= link_to 'Editar', edit_prova_path, :class => 'btn' %>
<%= link_to 'Voltar', provas_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#provas"
</script>