config/routes.rb
SisEscolar::Application.routes.draw do
  resources :provas

  resources :turma_materias

  resources :turmas

  resources :materias

  resources :professores

  resources :alunos

  root 'alunos#index'

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  # Aluno -> Turma_materia
  belongs_to :turma_materia, foreign_key: :turma_id

  # Aluno -> Turma
  belongs_to :turma

  # Apagando alunos apaga provas.
  has_many :provas, dependent: :delete_all
  accepts_nested_attributes_for :provas, :allow_destroy => true

  # nome e turma de aluno são campos obrigatórios
  validates_presence_of :nome, :turma_id

  # associando [prova] a [aluno]
  validates :nome, uniqueness: { scope: :turma_id, message: " já está matriculado nesta turma!" }
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  before_action :set_turmas, only: [:new, :edit, :update, :create]

  # GET /alunos
  # GET /alunos.json
  def index
    if params[:query]
      @alunos = Aluno.where("(LOWER(nome) like LOWER(:query))", {query: "%#{params[:query]}%"})
    else
      @alunos = Aluno.all
    end
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    set_turmas
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
    set_turmas
  end

  # POST /alunos
  # POST /alunos.json
  def create

    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno criado com sucesso!' }
        format.json { render action: 'show', status: :created, location: @aluno }
      else
        set_turmas
        format.html { render action: 'new' }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { head :no_content }
      else
        set_turmas
        format.html { render action: 'edit' }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # faz a busca para o select passando apenas as turmas que tem mais de 5 materias cadastradas
    def set_turmas
      @turmas = Turma.joins(:turma_materias).having("count(turma_materias.turma_id) > 4").group("turmas.id")
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:turma_id, :nome)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<!-- legenda -->
<legend>Matrícula</legend>

<!-- Mostra os erros -->
<% if @aluno.errors.any? %>
<div id="error_explanation">
  <h2><strong>Erros no preenchimento, verifique</strong></h2>
  <ul>
    <% @aluno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@aluno) do |f| %>

    <!-- Combo box com as turmas permitidas, maio que 5 materias -->
    <div class="field">
      <%= f.label :Turma %><br>
      <!-- Carregando a combo com os professores cadastrados no sistema e com o texto: Selecione um Professor -->
      <%= f.select(:turma_id, @turmas.collect {|p| [ p.nome, p.id ] }, { :selected => @aluno.turma_id}) %>
    </div>

    <!-- mostra informações -->
    <div class="field">
      <%= f.label :nome %><br />
      <%= f.text_field :nome %>
    </div>

    <!-- Botão voltar -->
    <%= f.submit class: "btn btn-primary", remote: false do %>
        <i class="icon-share-alt icon-white"></i>
    <% end %>
<% end %>

app/views/alunos/edit.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">
  <%= render 'form' %>
</div>

<!-- Botão para voltar a tela aluno aluno -->
<%= link_to 'Mostrar', @aluno, :class => 'btn' %>
<%= link_to 'Voltar', alunos_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#matriculas"
</script>

app/views/alunos/index.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">

  <!-- legenda -->
  <legend>Lista de Alunos</legend>

  <!-- Pesquisa -->
  <form class="navbar-form pull-right" style="padding-bottom: 20px;">
    <%= form_tag alunos_url, :method => :get, class: "navbar-search pull-right" do %>
        <%= text_field_tag(:query, ((params[:query])? params[:query].to_s : nil ), placeholder: "Pesquisar", class: "search-query") %>
        <%= submit_tag 'Buscar', :disable_with => "Buscando..." , :class=> "btn" %>
    <% end %>
  </form>

  <!-- tabela com a listagem -->
  <table class="table table-hover table-bordered">
    <thead>
    <tr>
      <th>Nome</th>
      <th>Turma</th>
      <th>Matriculado em</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.turma.nome %></td>

        <!-- apresentar a data de modificação no banco -->
        <td><%= aluno.created_at.strftime("%d/%m/%Y")  %></td>

        <!-- Visualizar -->
        <td width="30px">
          <%= link_to aluno, class: "btn btn-info", remote: false do %>
              <i class="icon-eye-open icon-white"></i>
          <% end %>
        </td>

        <!-- editar -->
        <td width="30px">
          <%= link_to edit_aluno_path(aluno), class: "btn btn-success", remote: false do %>
              <i class="icon-edit icon-white"></i>
          <% end %>
        </td>

        <!-- Deletar -->
        <td width="30px">
          <%= link_to aluno, method: :delete, data: { confirm: 'Você tem certeza?' } , class: "btn btn-danger", remote: false do %>
              <i class="icon-trash icon-white"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </table>
</div>

<!-- Btn add -->
<%= link_to 'Matricular aluno', new_aluno_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#matriculas"
</script>

app/views/alunos/new.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">
  <%= render 'form' %>
</div>

<br />

<!-- Botão voltar -->
<%= link_to 'Voltar', alunos_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#matriculas"
</script>

app/views/alunos/show.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">

  <!-- Legenda -->
  <legend>Aluno</legend>

  <p>
    <b>Nome:</b>
    <%= @aluno.nome %>
  </p>

  <p>
    <b>Turma:</b>
    <%= @aluno.turma_id %>
  </p>

</div>

<!-- Botão voltar -->
<%= link_to 'Editar', edit_aluno_path, :class => 'btn' %>
<%= link_to 'Voltar', alunos_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#matriculas"
</script>