config/routes.rb
SisEscolar::Application.routes.draw do
  resources :provas

  resources :turma_materias

  resources :turmas

  resources :materias

  resources :professores

  resources :alunos

  root 'alunos#index'

end

app/models/turma_materia.rb
class TurmaMateria < ActiveRecord::Base
  belongs_to :turma
  belongs_to :materia
  has_many :alunos

  # turma_id e materia_id são campos obrigatórios
  validates_presence_of :turma_id, :materia_id, message: "Campos em branco!"

  # associando [prova] a [aluno]
  validates :turma_id, uniqueness: { scope: :materia_id, message: " já contém esta matéria!" }
end

app/controllers/turma_materias_controller.rb
class TurmaMateriasController < ApplicationController
  before_action :set_turma_materia, only: [:show, :edit, :update, :destroy]

  # GET /turma_materias
  # GET /turma_materias.json
  def index
    if params[:form]
      @turma_materias = TurmaMateria.where("turma_id = :query", {query: params[:form][:turma_id]})
    else
      @turma_materias = TurmaMateria.all
    end
  end

  # GET /turma_materias/1
  # GET /turma_materias/1.json
  def show
  end

  # GET /turma_materias/new
  def new
    @turma_materia = TurmaMateria.new
  end

  # GET /turma_materias/1/edit
  def edit
  end

  # POST /turma_materias
  # POST /turma_materias.json
  def create
    @turma_materia = TurmaMateria.new(turma_materia_params)

    respond_to do |format|
      if @turma_materia.save
        format.html { redirect_to @turma_materia, notice: 'Turma materia was successfully created.' }
        format.json { render action: 'show', status: :created, location: @turma_materia }
      else
        format.html { render action: 'new' }
        format.json { render json: @turma_materia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turma_materias/1
  # PATCH/PUT /turma_materias/1.json
  def update
    respond_to do |format|
      if @turma_materia.update(turma_materia_params)
        format.html { redirect_to @turma_materia, notice: 'Turma materia was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @turma_materia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turma_materias/1
  # DELETE /turma_materias/1.json
  def destroy
    @turma_materia.destroy
    respond_to do |format|
      format.html { redirect_to turma_materias_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma_materia
      @turma_materia = TurmaMateria.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
    def turma_materia_params
      params.require(:turma_materia).permit(:turma_id, :materia_id)
    end
end

app/helpers/turma_materias_helper.rb
module TurmaMateriasHelper
end

app/views/turma_materias/_form.html.erb
<%= form_for(@turma_materia) do |f| %>

    <!-- Mostra os erros -->
    <% if @turma_materia.errors.any? %>
        <div id="error_explanation">
          <h2><strong>Erros no preenchimento, verifique</strong></h2>
          <ul>
            <% @turma_materia.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <!-- legenda -->
    <legend><%=  %>Turma e Materia</legend>

    <!-- mostra informações no select -->
    <div class="field">
      <%= f.label :Turma %><br>
      <%= f.collection_select(:turma_id, Turma.order(:nome), :id, :nome, :prompt => false) %>
    </div>

    <!-- mostra informações no select -->
    <div class="field">
      <%= f.label :Matéria %><br>
      <%= f.collection_select(:materia_id, Materia.order(:nome), :id, :nome, :prompt => false) %>
    </div>


    <!-- Botão gravar -->
    <%= f.submit class: "btn btn-primary", remote: false do %>
        <i class="icon-share-alt icon-white"></i>
    <% end %>
<% end %>

app/views/turma_materias/edit.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">
  <%= render 'form' %>
</div>

<!-- Botão para voltar a tela aluno aluno -->
<%= link_to 'Mostrar', @turma_materia, :class => 'btn' %>
<%= link_to 'Voltar', turma_materias_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#turmas"
</script>

app/views/turma_materias/index.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">

  <!-- legenda -->
  <legend>Lista de Turma e Matérias</legend>

  <!-- Pesquisa -->
  <form class="navbar-form pull-left" style="padding-bottom: 20px;">
  <%= form_tag turma_materias_path, method: :get do  %>
      <!-- mostra informações no select -->
      <div class="field">
        <%= label :form, :Turma %><br>
        <%= collection_select(:form, :turma_id, Turma.order(:nome), :id, :nome, :prompt => false) %>
        <%= submit_tag 'Buscar', :disable_with => "Buscando..." , :class=> "btn" %>
      </div>
  <% end %>
  </form>

  <!-- tabela com a listagem -->
  <table class="table table-hover table-bordered">
    <thead>
    <tr>
      <th>Turma</th>
      <th>Matéria</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @turma_materias.each do |turma_materia| %>
      <tr>
        <td><%= turma_materia.turma.nome %></td>
        <td><%= turma_materia.materia.nome %></td>

        <!-- Visualizar -->
        <td width="30px">
          <%= link_to turma_materia, class: "btn btn-info", remote: false do %>
              <i class="icon-eye-open icon-white"></i>
          <% end %>
        </td>


        <!-- Deletar -->
        <td width="30px">
          <%= link_to turma_materia, method: :delete, data: { confirm: 'Você tem certeza?' } , class: "btn btn-danger", remote: false do %>
              <i class="icon-trash icon-white"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </table>
</div>

<!-- Btn add -->
<%= link_to 'Adicionar matéria a turma', new_turma_materia_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#turmas"
</script>

app/views/turma_materias/new.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">
  <%= render 'form' %>
</div>

<br />

<!-- Botão voltar -->
<%= link_to 'Voltar', turma_materias_path, :class => 'btn' %>

app/views/turma_materias/show.html.erb
<!-- Caixa com fundo branco -->
<div class="box-header well">

  <!-- Legenda -->
  <legend>Turma e matéria</legend>

<p>
  <strong>Turma:</strong>
  <%= @turma_materia.turma.nome %>
</p>

<p>
  <strong>Materia:</strong>
  <%= @turma_materia.materia.nome %>
</p>


</div>

<!-- Botão voltar -->
<%= link_to 'Editar', edit_turma_materia_path, :class => 'btn' %>
<%= link_to 'Voltar', turma_materias_path, :class => 'btn' %>

<!-- destaca botão/menu fixo  -->
<script>
    menu = "#turmas"
</script>